[build]
command = "npm run build"
publish = "dist"

[build.environment]
NODE_VERSION = "22"
PUBLIC_SANITY_PROJECT_ID = "yllq4mvh"
PUBLIC_SANITY_DATASET = "production"
PUBLIC_SANITY_API_VERSION = "2026-04-19"
